__tests__/__snapshots__/index.test.js.snap, __tests__/index.test.js, components/Anchor.jsx, index.js
:---:|:---:
Updating sanitize attributes, add prop to Anchor, add test.
[ticket]: https://app.asana.com/0/695017019328171/1186360599081559
=> feat: allow download attribute in a tags

components/HTMLBlock.jsx
In compatibility mode, we `eval` inline scripts found in Custom HTML/CSS blocks. This logic fails on the server-side rendered pass for various reasons.
=> fix(compat mode): don't inject inline scripts on server

index.js
=> enhance: expose the core setup method

README.md, __tests__/index.test.js, components/Code/index.jsx, index.js, options.json
This adds a new `copyCodeButton` option to allow for the `CopyCode` button that's automatically inserted alongside `code` elements to not be added.
Adding this because in some cases within the API Explorer we have description markdown getting the copy button where it doesn't need to be, and with the way the CSS is set up in that project it's not easily pheasable to disable it otherwise.
=> feat: adding a new `copyButtons` option for disabling code copy btns

__tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/components.test.js, __tests__/magic-block-parser.test.js, index.js, processor/parse/magic-block-parser.js
:---:|:---:
Prep the markdown engine for readmeio/readme#3105.
=> feat: specify component-to-custom magic block mappings

components/Code/index.jsx, components/Code/style.scss, components/CodeTabs/index.jsx, package-lock.json, package.json
Been a while since the syntax highlighter has been updated here and since I added support for TOML to it today, we should get it up to date here so Markdown code blocks with that language should get highlighted.
* feat: adding support for TOML highlighting (#26) ([b2e617b](https://github.com/readmeio/syntax-highlighter/commit/b2e617b)), closes [#26](https://github.com/readmeio/syntax-highlighter/issues/26)
* fix: isolating regex check to highlightmode option (#25) ([aec7c81](https://github.com/readmeio/syntax-highlighter/commit/aec7c81)), closes [#25](https://github.com/readmeio/syntax-highlighter/issues/25)
* fix: check for \n in CodeMirror runmode (#23) ([66444f4](https://github.com/readmeio/syntax-highlighter/commit/66444f4)), closes …
=> chore(deps): upgrading `@readme/syntax-highlighter`

.eslintrc, __tests__/__snapshots__/flavored-parsers.test.js.snap, __tests__/flavored-parsers.test.js, package-lock.json, package.json, processor/parse/flavored/code-tabs.js
:---:|:---:
The previous regex had problems matching on poorly formatted markdown.
This one attempts to use a more precise regex to match adjacent code
blocks. It does fail the linter's unsafe-regex check, but I belive that
it's safe from 'catastrophic' backtracking. IIUC the negative lookahead
should mean there's only one way to match the nested matchers.
[ticket]: https://app.asana.com/0/1198968777158470/1198971573743122/f
=> fix: tabbed code block regex

components/Callout/index.jsx
:---:|:---:
This removes a call to .splice() on the Callout component's children.
Modifying the children meant that the component couldn't render twice,
which happens when the callout is pinned to the sidebar. It's rendered
once for spacing, then again for display.
Writing a test using enzyme is somewhere between not possible and
contrived. A follow-up PR in the api-explorer will test this.
#35 
[ticket]: https://app.asana.com/0/1178132843162889/1198496636781214/f
=> fix: pinned callouts dont render body

__tests__/components.test.js, __tests__/helpers.js, __tests__/magic-block-parser.test.js, __tests__/magic-block-parser/__snapshots__/table.test.js.snap, __tests__/magic-block-parser/table.test.js, jest.config.js, processor/parse/magic-block-parser.js
The old magic block syntax allowed shrinking the dimensions of a table,
and would leave the data in place. Unknown if that's a bug or a feature.
In any event, the new engine should needs to handle that.
=> fix(magic-block-parser): handle excess table data

.github/workflows/bundlewatch.yml, package.json
Configures [Bundlewatch](https://bundlewatch.io) to help us keep bundle sizes in check. Bundle limit is currently set at 1MB for gzipped files.
=> ci: setting up bundlewatch

package-lock.json, package.json, webpack.config.js
This starts treating `react` and `react-dom` as peerDependencies and Webpack externals. They'll no longer be incorporated into our compiled dist files. Unfortunately there doesn't seem to be much difference in the size of the dist, but this should reduce the possibility of differing React versions from clashing with each other in other integrations that us this library.
=> feat: treat react and react-dom as external deps

.github/workflows/release.yml, .releaserc
:---:|:---:
Add a `@next` release channel to the NPM package in order to better test and run ReadMe-side integrations off the next branch.
=> feat(release): add a next channel

package-lock.json, package.json
Pull in updates to our various `@readme` packages.
=> chore(deps): bump @readme packages

.github/workflows/bundlewatch.yml, .github/workflows/ci.yml, .github/workflows/release.yml
Our bundle analysis CI/CD workflow was running on release commits, as you can see [here](https://github.com/readmeio/markdown/runs/1571530277).
https://github.com/readmeio/markdown/blob/2d30f3afc32756b40cbfcbba734f80ea9400a9e5/.github/workflows/bundlewatch.yml#L8
=> fix(bundlewatch): honor skip commit message

package.json
=> chore: don't run eslint on `test.watch`

__tests__/components/HTMLBlock.test.jsx
Avoid leakage of Jest globals per @kellyjosephprice's [comment](https://github.com/readmeio/markdown/pull/100#discussion_r545290710)...
=> test(HTMLBlock): move globals setup into `beforeEach` block

docs/callouts.md, docs/custom-css.md, docs/embeds.md, docs/getting-started.md, docs/images.md, docs/lists.md, docs/tables.md
=> docs: update docs to latest markdown

sanitize.schema.js
:---:|:---:
Per some of the changes I'm working on to how our recipes embeds work in the guides section, I need to add `slug` to the attribute whitelist!
[ticket]: https://linear.app/readme-io/issue/RM-23/guides-embed-should-open-modal-directly
=> fix(recipes): add 'slug' to whitelist

components/Callout/style.scss, example/Demo.jsx, example/demo.scss
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes CX-16
:---:|:---:
* reverts removing left padding from lists in callouts
[demo]: https://markdown-pr-126.herokuapp.com/#callouts
[prod]: https://kjp.readme.io/docs/content
=> fix: add back padding to lists in callouts

docs/getting-started.md
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo]
:---:
=> docs: add disable tokenizers

components/Table/style.scss
:---:|:---:
RDMD tables hide overflow content (in order to achieve some fancy `border-radius` shit) [which cuts off glossary terms' written in table cells][broke]!
[broke]: https://developers.logitech.com/circle/reference/notification-events?enableNewMarkdown=true
=> style: fix glossary term overflow in tables

package.json
This loosens up the version constraints on our `@readme/variable` peerDep as right now that package is the API Explorer repo and occasionally receives a version bump when we update dev dependencies, and right now when that happens we receive this error on npm@7 when doing installs:
```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @readme/explorer@0.0.0
npm ERR! Found: @readme/variable@12.0.0
npm ERR! node_modules/@readme/variable
npm ERR!   dev @readme/variable@"^12.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @readme/variable@"^11.0.0" from @readme/markdown@6.26.0
npm ERR! node_modules/@readme/markdown
npm ERR!   dev @readme/markdown@"^6.21.0" from the root project
npm …
```
=> chore: loosening up our @readme/variable peerDep

components/Code/index.jsx
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | See: [@readme/syntax-highlighter#94][94]
:---:|:---
If you write a code block, the RDMD engine will wrap the code contents with a `div`. Unfortunately, this holds true for inline code snippets as well, since they're represented by the same underlying MDAST. [Per the W3][w3], `<p>` tags may *only* contain other inline elements, which means the engine throws a warning whenever we render an inline code snippet within a paragraph. Which is, like, all the time...
To fix this, we added an `inline` toggle to our syntax highlighter ([#94][94]) to optionally use a `<span>` instead of a `<div>`. So here, we need to:
The existence of a custom `lang` attribute is a decent proxy for inline versus code blocks. (And even if …
=> fix(code): silence DOM errors for inline snippets in p tags

__tests__/magic-block-parser.test.js, processor/parse/magic-block-parser.js
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | 💬  [Thread][thread]
:---:|:---:
In certain, very specific scenarios, empty magic image blocks would throw an error on parse:
- [~Working in this PR app~][demo].
[demo]: #tktktk "Pending an integration branch in ReadMe..."
[prod]: https://dev.kanad.dev/docs/empty-image-block
[thread]: https://readmeio.slack.com/archives/CC96MKA1E/p1620138248049400
=> fix(image): filter null magic blocks

components/Table/style.scss
=> style(tables): hide empty table header rows

docs/callouts.md, docs/code-block-tests.md, docs/code-blocks.md, docs/custom-css.md, docs/embeds.md, docs/features.md, docs/getting-started.md, docs/headings.md, docs/images.md, docs/lists.md, docs/syntax-extensions.md, docs/table-of-contents-tests.md, docs/tables.md, docs/variable-tests.md
:---:|
It appears that the rdme docs sync step of our release CI is failing: https://github.com/readmeio/markdown/runs/2833856744
```
Error: We couldn't save this doc (Path `category` is required.).
```
This commit adds the category in the front-matter of each page we're syncing! I have some doc updates in the pipeline (will open a separate PR for them!) but wanted to make sure this was resolved first.
[demo]: https://markdown-pr-171.herokuapp.com
=> docs: add category to each page

docs/custom-css.md
:---:|
Updates our Custom CSS guidance to reflect the updated markup in the new docs design!
[demo]: https://markdown-pr-172.herokuapp.com
[prod]: https://rdmd.readme.io/docs/custom-css
=> docs: update custom CSS guidance

docs/callout-tests.md
So it looks like the sync step was _**partiallly**_ fixed in #171 (see [this page](https://rdmd.readme.io/docs/custom-css), which successfully updated!), but there was one page that I overlooked which ultimately [caused the workflow to fail](https://github.com/readmeio/markdown/runs/2896825988?check_suite_focus=true#step:8). Since this is a simple test page, I'm just backfilling the category for this page with our existing catch-all "Tests" category.
I actually ran the `rdme` command locally this time and confirmed that the script ran successfully 🎉  If I am not crazy and you can in fact see [this page](https://rdmd.readme.io/docs/callouts-tests) in ReadMe, we should be good to go! See below for the full output when I ran the command locally:
=> ci: add another missing page category to get our docs syncing

package-lock.json, package.json
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | 
:---:|
Mostly a maintenance release but this does add support for highlighting JSX.
* chore(deps-dev): bump @babel/preset-env from 7.13.12 to 7.13.15 (#108) ([0462a05](https://github.com/readmeio/syntax-highlighter/commit/0462a05)), closes [#108](https://github.com/readmeio/syntax-highlighter/issues/108)
* chore(deps-dev): bump @babel/preset-env from 7.13.15 to 7.14.0 (#113) ([6909bd9](https://github.com/readmeio/syntax-highlighter/commit/6909bd9)), closes [#113](https://github.com/readmeio/syntax-highlighter/issues/113)
* chore(deps-dev): bump @babel/preset-env from 7.14.0 to 7.14.4 (#129) ([cab7498](https://github.com/readmeio/syntax-highlighter/commit/cab7498)), closes …
=> chore(deps): upgrading syntax-highlighter to 10.8.0

__tests__/index.test.js, index.js, variable/index.jsx
=> fix: typos in variable subpackage exports

index.js, processor/parse/flavored/callout.js
:---:|
Export the callout emoji map so it can be consumed by the markdown editor.
[demo]: https://markdown-pr-219.herokuapp.com
=> feat: export callout icons

components/Code/index.jsx
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes RM-1535
:---:|:---:
Added `aria-label` to button.rdme-code-copy.fa to make it accessible. Follow the links below and go to Lighthouse under dev tools, run the accessibility check, and you'll see that the buttons is now passing accessibility check!
[demo]: https://markdown-pr-228.herokuapp.com
[prod]: https://docs.readme.io/docs/custom-login-with-readme
=> fix(a11y): making copy code button accessible

README.md
@mjcuva pointed out that we make no reference to the local development environment in our docs!
=> docs(readme): add Local Development section

package-lock.json, package.json
:---:|
* feat: stringify object values (#24) ([1936d63](https://github.com/readmeio/variable/commit/1936d63)), closes [#24](https://github.com/readmeio/variable/issues/24)
* feat: upgrading our build process to webpack 5 (#23) ([de0df3e](https://github.com/readmeio/variable/commit/de0df3e)), closes [#23](https://github.com/readmeio/variable/issues/23)
* chore(deps-dev): bumping dev deps ([ae8e8b6](https://github.com/readmeio/variable/commit/ae8e8b6))
* ci: setting up codeql ([f4127de](https://github.com/readmeio/variable/commit/f4127de))
* docs: adding a security policy ([5560b8d](https://github.com/readmeio/variable/commit/5560b8d))
* chore(deps-dev): bump babel-jest from 27.0.6 to 27.1.0 (#166) …
=> chore(deps): bumping @readme/syntax-highlighter and @readme/variable

package-lock.json, package.json
:---:|
This bumps `@readme/syntax-highlighter` to allow for us to start highlighting GraphQL code. Available code language modes (the language that comes after the 3 backticks) that we'll support are `graphql` and `gql`.
* docs: adding a code of conduct ([41d91b5](https://github.com/readmeio/syntax-highlighter/commit/41d91b5))
* feat: adding highlight support for graphql (#173) ([8ffcb52](https://github.com/readmeio/syntax-highlighter/commit/8ffcb52)), closes [#173](https://github.com/readmeio/syntax-highlighter/issues/173)
[demo]: https://markdown-pr-309.herokuapp.com
[prod]: https://rdme.readme.io
=> chore(deps): bumping syntax-highlighter to support graphql

components/Code/index.jsx
The ReadMe test suite was failing catastrophically because we were loading codemirror in the node environment.
=> fix: dont load codemirror in node

package.json
Update the npm registry URL to use TLS.
=> fix: use TLS for npm release

__tests__/__snapshots__/index.test.js.snap, __tests__/flavored-parsers/callouts.test.js, __tests__/index.test.js, __tests__/table-flattening/index.test.js, index.js
:---:|
Allows starting a markdown doc with indented code. It looks like we were trimming off all whitespace, which mess with leading indented code blocks.
[demo]: https://markdown-pr-362.herokuapp.com
[prod]: https://kjp-examples.readme.io/docs/leading-code-indentation
=> fix: allow indented code on first line

__tests__/__snapshots__/flavored-compilers.test.js.snap, __tests__/flavored-compilers.test.js, processor/compile/embed.js, processor/compile/figure.js, processor/compile/image.js, processor/compile/index.js, processor/parse/magic-block-parser.js
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes RM-2780
:---:|:---:
Fixes converting mdast to md for some node types.
<dl>
<dt>emojis</dt>
<dd>Were saving as images, now they save in the short code format.</dd>
<dt>embeds</dt>
<dd>Were saving as links, now they save in magic block format. This decision was made for expediency. To eventually save them as links, we ought to update RDMD to parse link formatted embeds.</dd>
<dt>figures</dt>
<dd>Were saving as images, now they save in magic block format. Until we decide on a proper syntax for captions and sizing, we're forced to use magic block format.</dd>
</dl>
[demo]: https://markdown-pr-377.herokuapp.com
=> feat: less lossy md()

__tests__/flavored-compilers.test.js, processor/compile/glossary.js, processor/compile/html-block.js, processor/compile/index.js
Adds compilers for `html-block` and `readme-glossary-item`.
=> feat: more compiler updates

__tests__/components/Code.test.jsx, components/Code/index.jsx, package-lock.json, package.json
:---:|
It's possible to generate a react tree with an empty code block. This adds checks to the Code component to allow this.
Example:
```
<code></code>
```
[prod]: https://dash.readme.com/project/kjp/v1.0/docs/empty-code-block
=> fix: allow undefined code children

package-lock.json, package.json
Having issues upstream in ReadMe with the latest `@readme/syntax-highlighter` and its fresh release of `codemirror` so I bumped it back down.
See https://github.com/readmeio/syntax-highlighter/pull/222 for details.
=> fix: bumping @readme/syntax-highlighter to resolve upstram webpack issues

package-lock.json, package.json
The ongoing quest to get `@readme/syntax-highlighter` upgraded and working in the dash/hubs.
=> fix: upgrading syntax-highlighter to the latest release

__tests__/__snapshots__/flavored-compilers.test.js.snap, __tests__/flavored-compilers.test.js, processor/compile/figure.js, processor/compile/image.js, processor/parse/magic-block-parser.js
:---:|
Adds support for saving images without captions but with widths.
=> feat: add width support to image compiler

__tests__/flavored-parsers.test.js, processor/parse/flavored/code-tabs.js
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes (part of) 3457
:---:|:---:
We found that the code tabs parser would break if we had an empty tab. According to the tab's contents and the order it was added to the set of code blocks, it could be rendered with or without an empty line space.
This change to the regex allows the parser to understand that a tab without an empty line is still a tab. 
=> fix: code block regex should allow empty tab contents

__tests__/components/TableOfContents.test.jsx, __tests__/components/__snapshots__/TableOfContents.test.jsx.snap, components/TableOfContents/index.jsx
Makes a tiny markup change to our TOC so we can address this issue that's getting flagged in our Lighthouse SEO score:
Do tests pass?
=> fix(SEO): add href to TOC

__tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/magic-block-parser.test.js, processor/parse/magic-block-parser.js
(relates to [RM-74](https://linear.app/readme-io/issue/RM-74))
We're seeing an issue in the new embed block where the page crashes when trying to render a populated embed. Here's a video of me having a lovely time with it, entering the (valid) YouTube URL https://www.youtube.com/watch?v=tE0wh-RKhR0:
https://user-images.githubusercontent.com/48635728/158707361-47e3342f-eb71-4c65-9109-f3f68ce1a135.mov
The error returned is this one:
We've tracked this down to [the switch statement inside magic-block-parser,](https://github.com/readmeio/markdown/blob/b0e98ac373d3985ac9eaa40bff3fde2cb93c38a9/processor/parse/magic-block-parser.js#L202), where we assign a value to `json.provider`.
We go on to use this `json.provider` as a title [here](https://github.com/readmeio/markdown/blob/b0e98ac373d3985ac9e …
=> fix: page crashing on invalid url in embed block

.github/workflows/release.yml, .releaserc
This reverts the "fix" in #450 that... didn't actually fix anything 😭 
Per [the conversation in Slack](https://readmeio.slack.com/archives/C5B798RFZ/p1647541885461399), we are no longer running the release workflow in `next`. Still not sure why it broke in the first place though 🤔 
Also doing a bit of cleanup in our workflow file: getting rid of the redundant matrix strategy line, formatting, etc.!
Don't think we'll know until this is in `main` ¯\_(ツ)_/¯
=> ci(release): don't run on next, cleanup

styles/gfm.scss
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes RM-1395 | RM-6415
:---:|:---:|:---:
Adds a class for when we start inserting blank lines.
You can try inserting the following markdown:
```
One line
<p class="blank-line"></p>
Another line
```
And you should see 3 paragraphs of similar heights.
[demo]: https://markdown-pr-457.herokuapp.com
=> style: add class for blank-line

__tests__/flavored-compilers.test.js, processor/compile/i.js, processor/compile/index.js
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes RM-3937
:---:|:---:
Adds a compiler for the `i` type, font-awesome emojis. This is so the editor can save back out when loading, for instance: `:fa-rss-square:`.
=> fix(gemoji): add compiler for font-awesome emojis

.github/PULL_REQUEST_TEMPLATE.md
Updates the PR template to match what we're using in our other repos now and also to mainly fix the broken icon image.
=> docs: updating the pr template

__tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/magic-block-parser.test.js, components/Embed/index.jsx
[![PR App][icn]][demo] | Fix RM-4083
The old editor used to produce empty embed magic blocks whose markdown looked like this:
```
[block:embed]
{}
[/block]
```
For the new editor's magic block embed, the empty state looks like this:
```
[block:embed]
{
"url": "",
"typeOfEmbed": "pdf",
"provider": "embed"
}
[/block]
```
(for a PDF, for example).
Instead of disappearing the empty block, the new empty state was being rendered as the following in the hub:
With this PR, we're back to disappearing the empty magic block.
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-0 …
=> fix: new editor magic block embed empty state

__tests__/__snapshots__/flavored-compilers.test.js.snap, __tests__/flavored-compilers.test.js, processor/compile/index.js, processor/compile/table.js
[![PR App][icn]][demo] | Fix RM-4110
Magic block tables preserve breaks. Typically, RDMD writes tables to markdown as github flavored tables, which do not support any block content, including breaks.
This adds a custom compiler that checks if there are breaks in the table, in which case, it saves as a magic black table.
[demo]: https://markdown-pr-467.herokuapp.com
=> fix(tables): preserve breaks in tables

__tests__/flavored-compilers/break.test.js, processor/compile/break.js, processor/compile/index.js
[![PR App][icn]][demo] | Fix RM-4096
Override the `break` compiler to save as "&blank;&blank;\n" instead of "\\\n".
The MarkdownEditor doesn't use the `escape` parser, so that the backslashes are preserved in the editor. For some reason `remark-parse` doesn't consume the backslash of "\\\n" when parsing the break. (I believe this is technically incorrect, but :shrug:) This means that if you enter a newline in the editor, it gets saves as "\\\n" and then loaded as the same.
We can't turn the `escape` parser on, as we'd lose escapes. And, we could save as "\n" when `correctnewlines: false`, but that's not portable to other markdown parsers. So this seems like a reasonable workaround.
[demo]: …
=> feat: save newlines with spaces

__tests__/__snapshots__/flavored-compilers.test.js.snap, processor/compile/image.js
[![PR App][icn]][demo] | 
In order to allow images in tables, we're going to save them in markdown format when they don't have a width, so we don't try to nest magic blocks (images saved as figures) within magic blocks (tables).
=> fix: save images in markdown format when they don't have a width

__tests__/GlossaryItem.test.jsx, components/GlossaryItem.jsx
=> Glossary fixes

.github/workflows/autodeploy.yaml
This configures a GitHub Action to automatically deploy the Heroku app `markdown-demo` whenever changes are pushed to the `next` branch of this (`readmeio/markdown`) repo. This essentially restores the auto-deploy feature that we lost in the Great Heroku Security Mess! But it doesn't bring back automatic PR review apps just yet.
@erunion @domharrington @rafegoldberg @kellyjosephprice (Y'all seem to be active in this repo) Heads up that this will change the behavior of this repo, and will start publishing `main` commits directly to production again. You can see the status of the deploy on [the "Actions" tab of this repo](https://github.com/readmeio/markdown/actions), and also in [the "Activity" tab of the Heroku app](https://dashboard.heroku.com/apps/markdown-demo/activity).
=> chore: auto-deploy changes to Heroku (markdown-demo)

__tests__/__snapshots__/flavored-compilers.test.js.snap, __tests__/flavored-compilers/tables.test.js, processor/compile/table.js
[![PR App][icn]][demo] | Fix RM-4309
The custom table compiler was not correctly saving back to magic block :(.
=> fix(table): correctly save magic block

__tests__/__snapshots__/disabling-tokenizers.test.js.snap, __tests__/flavored-parsers/__snapshots__/compact-headings.test.js.snap, __tests__/flavored-parsers/compact-headings.test.js, processor/parse/compact-headings.js
[![PR App][icn]][demo] | Fix RM-4298
We used to have a custom tokenizer to allow headers without a space between the # char and the heading content. It was resulting in the position data being skewed, which then meant that when we tried to normalize links in headers in the editor ([over here in this file](https://github.com/readmeio/readme/blob/1a8da465ae7775d1e189fc060256edfcae7aa75c/packages/react/src/ui/MarkdownEditor/editor/blocks/Link/normalizeNode.ts)) we crashed the page.
We've now adapted our tokenizer to closely follow remark-parse's approach (as [defined here](https://github.com/remarkjs/remark/blob/remark-stringify%407.0.2/packages/remark-parse/lib/tokenize/heading-atx.js)) but adapted the regex we match against to allow those cases without a …
=> fix: swap out our custom heading tokenizer to more closely follow remark-parse

__tests__/flavored-compilers/images.test.js, processor/compile/image.js
[![PR App][icn]][demo] | Fix RM-4329
Saving images in tables was busted. The compiler needed some null checks. It looks like the editor was nicely inserting the `hProperties` when it had a 'full' image, but not when it was in a table.
=> fix: serializing images 😬

__tests__/flavored-compilers/escape.test.js, __tests__/flavored-parsers/__snapshots__/escape.test.js.snap, __tests__/flavored-parsers/escape.test.js, processor/compile/escape.js, processor/compile/index.js, processor/parse/escape.js, processor/parse/index.js
[![PR App][icn]][demo] | Fix RM-4340
Adds an 'escape' type.
Our markdown editor has no way to discern if an element has been escaped or not. Consider the markdown:
```
\&para;
```
This will be represented in `mdast` roughly as:
```
{
type: 'text',
value: '&',
}, {
type: 'text',
value: 'para;'
}
```
This PR changes that to:
```
{
type: 'escape',
value: '&',
}, {
type: 'text',
value: 'para;'
}
```
This will enable our editor to re-add the necessary backslash.
=> feat: add escape type

.github/workflows/review-app.yaml
This uses [our new GitHub Action for managing Heroku review apps](https://github.com/readmeio/heroku-review-app-action) to deploy review apps for Markdown, just like it worked before April 15.
* When a Pull Request is opened or reopened, a review app is created in the [`markdown` pipeline](https://dashboard.heroku.com/pipelines/ab10f22a-8076-49ce-8e4f-5968280b2e59) on Heroku
* When a Pull Request is [synchronized](https://github.community/t/what-is-a-pull-request-synchronize-event/14784), the review app is rebuilt with the latest source
* When a Pull Request is closed, the review app is deleted
For more information, check out the GitHub Action repo linked above.
=> chore: auto-open Markdown review apps on Heroku

__tests__/flavored-compilers/yaml.test.js, processor/compile/index.js, processor/compile/yaml.js
[![PR App][icn]][demo] | Fix RM-4430
Adds a compiler for frontmatter.
If you try to save a doc in the editor with frontmatter, the save currently fails! Something like the following:
```
---
title: Getting started
---
Coming content
```
[demo]: https://markdown-pr-509.herokuapp.com
[prod]: https://dash.readme.com/project/pismo-docs/v1.0/docs/old-draft-authentication-with-openid-connect-for-servers
=> feat: add yaml compiler

README.md, __tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/components/HTMLBlock.test.jsx, __tests__/index.test.js, components/HTMLBlock/index.jsx, components/HTMLBlock/style.scss, components/index.js, example/Demo.jsx, example/Fixtures/docs.js, example/Fixtures/index.jsx, example/demo.scss, index.js, options.js, processor/parse/magic-block-parser.js, styles/components.scss
[![PR App][icn]][demo] | Fix RM-4509
Adds a `safeMode` flag. When run with `safeMode: true`, we no longer render html blocks. This is to prevent a wide range of vulnerabilities that are available via iframes, script tags, and attributes that allow javascript.
There are cases where we want to render 'untrusted' markdown (via suggested edits). Since we want to still allow the full range of html within html blocks, but we also need to be able to render untrusted changes, this seemed like a good compromise.
You can try it out in the [PR app][demo]. The 'getting started' page has a short html block at the bottom. If you enable the `safeMode` flag, you should be able to see it render as a `<pre>` element.
- [Working in this PR …
=> feat: add safeMode flag

__tests__/components/HTMLBlock.test.jsx, components/HTMLBlock/index.jsx
[![PR App][icn]][demo] | Fix RM-4509
This actually escapes html characters when rendering them via `safeMode`. :grimacing:
=> fix: escape html when rendering in safeMode

__tests__/components/HTMLBlock.test.jsx, components/HTMLBlock/index.jsx, package-lock.json, package.json
[![PR App][icn]][demo] | Fix RM-4509
Uses an escape function that works in node, for when rendering html via `safeMode`.
=> escapes support node

CHANGELOG.md, __tests__/components/HTMLBlock.test.jsx, components/HTMLBlock/index.jsx, package-lock.json, package.json
[![PR App][icn]][demo] | Fix RM-4509
Ugh. Correctly render escaped html by setting it via `dangerouslySetInnerHtml`.
=> fix escaping again

docs/getting-started.md, example/Fixtures/index.jsx, example/demo.scss
[![PR App][icn]][demo] | [PR App][demo] 
:----------------------:|:--------------:
Open up the [demo app for this PR][demo], resize your browser so it's very short, and then try scrolling the left hand content panel. Only the top-most *Fixture* section should stick to the top!
[demo]: https://markdown-pr-523.herokuapp.com
=> style(demo): polish sticky scrolling

__tests__/components/HTMLBlock.test.jsx
[![PR App][icn]][demo] | Fix RM-4673
This PR adds some additional tests for executing scripts within html blocks. Github had flagged the regex we use to extract scripts as a potential vulnerability. It pointed out two things:
1. Html closing tags will happily render with arbitrary attributes, so trying to match something simple like `/</script>/` is insufficient.
2. That there are so many edge cases, that it's safer to rely on well tested libraries for parsing html.
In testing these assertions, our code appears to be safe since `innerHtml` no longer will execute `script` tags. Presumably since it was such a common attack vector. In any event, I thought it'd be good to keep the tests around.
- [Working in this PR …
=> test: add additional script sanitizing tests

__tests__/astToPlainText.test.js, __tests__/table-flattening/index.test.js, index.js, package-lock.json, package.json, processor/plugin/plain-text.js
[![PR App][icn]][demo] | Fix RM-3436
Fixes the `astToPlainText` compiler.
I'm not sure how this working at all before, sometimes it returns a string, and sometimes it returns the passed in node?! Prior to this, it was calling `.runSync(ast)` which only [runs the `run` step](https://github.com/unifiedjs/unified#overview) and only calls `transformers` on the passed in `ast`. Theoretically, the correct call should be `.stringify(ast)`, which calls the `compile` step. 
This PR reworks `astToPlainText()` to make the 'correct' call to `.stringify(ast)`. It also copies in the `hast-util-to-string` library so that it will use a space (` `) to join all the strings together.
[demo]: …
=> feat: fix plain string compiler

__tests__/__snapshots__/flavored-parsers.test.js.snap, __tests__/flavored-parsers.test.js, processor/parse/flavored/code-tabs.js
[![PR App][icn]][demo] | Fix RM-4689
We were trimming the leading whitespace from code blocks, which offsets indentations for lines when leading whitespace is intended on the first line of a code block. This PR resolves that by replacing the trim() method with the replace() to specifically target a remove new lines at the start of a code block as opposed to removing all leading whitespace.
[demo]: https://markdown-pr-552.herokuapp.com/
[prod]: http://project-display.next.readme.ninja/docs/code-indentation
=> fix: correct first line spacing in code blocks

__tests__/astToPlainText.test.js, processor/plugin/plain-text.js
Use the images title when converting to plain text. This is useful for search indexing.
=> fix: images to plain text

__tests__/astToPlainText.test.js, __tests__/table-flattening/index.test.js, processor/plugin/plain-text.js
Fixes images to plain text when they are the only node passed to `astToPlainText`
=> fix: images to plain text at the root

__tests__/astToPlainText.test.js, processor/plugin/plain-text.js
Yet another fix to `astToPlainText`, this time when there is a single image passed in, and that image has empty children. I'm not sure where the empty children are coming from, but this fix seems reasnable enough.
=> fix: astToPlainText with lone image

__tests__/flavored-parsers/callouts.test.js, processor/parse/flavored/callout.js
- Switch order of callout warning icons (🚧 <-> ⚠️)
- Based off the [docs](https://rdmd.readme.io/docs/callouts), the default should be 🚧 instead of ⚠️
=> fix: callout warning icon

__tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/index.test.js, __tests__/magic-block-parser.test.js, index.js, options.js, processor/parse/magic-block-parser.js
[![PR App][icn]][demo] | Fix RM-4798
We want to better handle errors when trying to parse magic blocks; previously we were failing more or less silently (apart from an error in the console) and disappearing magic blocks with invalid JSON. We're not keen on the disappearing act when toggling from raw mode to the new editor, so this PR:
1. adds a flag called `alwaysThrow`, set to `false` by default
2. when this flag is set to true, throw a new error when failing to parse the json in a magic block
We'll still log out to the console in both cases- this ensures we aren't changing the behavior of the old editor and continues to provide extra context for the user if they want it/know it's there.
This is PR 1/3 for this ticket. 
PR 2/3 will be updating the …
=> feat: throw when parsing invalid magic block json

__tests__/__snapshots__/index.test.js.snap, __tests__/index.test.js, components/Anchor.jsx
[![PR App][icn]][demo] | Fix RM-2485
There's a bug with our [internal link](https://docs.readme.com/docs/linking-to-pages#internal-links) feature where if you pass a url hash of non-unicode characters as an anchor link, the `href` doesn't get parsed in the `Anchor` component. 
Here's an example: https://busted-links.readme.io/docs/intercom-3
- Ignore anchor hash when parsing internal link syntax that generates a link's path, and append the hash to the path string separately.
=> fix(anchor): ignore anchor hash when parsing internal link syntax

__tests__/__snapshots__/flavored-compilers.test.js.snap, __tests__/flavored-compilers.test.js, processor/compile/figure.js, processor/compile/image.js
[![PR App][icn]][demo] | Fix RM-XXX
feat: ensure bordered images are rendered via a magic block
=> feat: ensure bordered images are rendered via a magic block

__tests__/components/Code.test.jsx, components/Code/index.jsx
[![PR App][icn]][demo] | Fix RM-5222
This is a bit more semantic and therefore helps Localize, which we use for translations, parse our html correctly.
Tried a few other things before going with this approach. One thought was that we could just not render the button at all for inline code. Unfortunately there isn't a very easy way to distinguish between inline vs block code. We use the presence of a `lang` property in the props as a proxy, but you can definitely have a code block with no lang, so I didn't feel that was accurate enough. Also my assumption is that this translation parsing issue could still be present for code blocks, so this is just the safer approach.
Visually this ends up looking exactly the same given we're only ever …
=> fix: avoid nesting button in code block

components/GlossaryItem/style.scss
Dark mode for Glossary tooltips
=> style(glossary): dark mode

processor/parse/flavored/callout.js
In a previous PR, I refactored the callout parser, and it was no longer trimming the titles.
=> fix: trim callout titles

__tests__/__snapshots__/html-block-parser.test.js.snap, __tests__/flavored-compilers.test.js, __tests__/html-block-parser.test.js, index.js, processor/parse/html-block.js, processor/parse/index.js
It's endlessly frustrating that remark <= v7 uses the same type for block and inline html. Today, I did something about it.
=> feat: html block

components/Table/style.scss
[![PR App][icn]][demo] | Fix RM-5246
Displays borders on empty th's.
=> style: show border for empty th

__tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/magic-block-parser.test.js, processor/parse/magic-block-parser.js
[![PR App][icn]][demo] | Fix RM-5725
The following block was crashing the editor, with the TypeError `node.children.map is not a function`:
```
[block:api-header]
{
"type": "basic"
}
[/block]
```
It's somewhat of a mystery to me how this type of empty api header magic block is ending up in our customers' markdown anyway, because an empty header inserted in the old editor looks like
```
[block:api-header]
{}
[/block]
```
and an empty header inserted in the new editor looks like `##` (or similar). My best guess is that this is somehow a legacy bug, from a time when api-header magic blocks had a different shape?
The error was being thrown in our `reactTOC` function, when we [try to normalize heading …
=> fix: blank api headers crashing reference pages

index.js
Makes `rdmd.utils.options` a new object on each `get`. Hopefully this fixes cases where `options` is being overwritten.
=> fix: immutable options

docs/callouts.md
I noticed that [this page](https://docs.readme.com/rdmd/docs/callouts) has a typo in the title:
I dug a little deeper and realized we have the `title` + `description` metadata hardcoded in this file for some reason. I'm guessing this was added at some point for testing purposes, but I'm cleaning this up a bit both to fix the typo and just to ensure that the page contents actually match the metadata if we ever make changes in the future.
=> docs(callouts): remove unnecessary metadata

__tests__/__snapshots__/index.test.js.snap, __tests__/components/Image.test.jsx, components/Image/index.jsx, components/Image/style.scss
[![PR App][icn]][demo] | Fix CX-151
Used the correct value for the align attribute. Chrome for some reason allows images to be centered via `[align=center]`. But this isn't strictly correct: [The Image Embed element | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#deprecated_attributes)
Firefox only recognizes 'middle' and not 'center'.
=> fix: centering in firefox

sanitize.schema.js
| [![PR App][icn]][demo] | Fix SA-13 |
| :--------------------: | :-------: |
Adds `colgroup` and `col` to the allow list. No idea why these were being filtered?!
=> feat: allow colgroup + col

package-lock.json, package.json
I've added improved highlighting for the Solidity language in https://github.com/readmeio/syntax-highlighter/pull/435, this pulls that work in here.
=> chore(deps): bumping syntax-highlighter

styles/gfm.scss
Adds what appear to be a bunch of missing semi-colons.
IIUC, scss requires semi-colons, so I have no idea how this worked before?
=> fix: add css semi-colons

components/GlossaryItem/style.scss
[![PR App][icn]][demo] | Fix CX-386
[slack thread](https://readmeio.slack.com/archives/C0101J0HU1Z/p1687274834378059)
| before | after |
|--------|--------|
| <img width="80" alt="image" src="https://github.com/readmeio/markdown/assets/43232318/d53370dd-2e61-4c61-b104-e902d2c43787"> | <img width="90" alt="image" src="https://github.com/readmeio/markdown/assets/43232318/e013b8b4-5b59-44cb-9d1a-92ea69006876"> | 
- Fix `border-left` and `border-right` styles applying dotted lines incorrectly due to [changes in ordering](https://github.com/readmeio/markdown/pull/756/files#diff-0f5fbef626dd723f36428180e061af1a110698f6f9ad519a92e29c297451fb12R4-R10)
- Remove `border-style: dotted` and just replace `solid` with `dotted` in `border-bottom`
- [Broken on …
=> fix: glossary item border styles

components/Code/style.scss, components/CodeTabs/style.scss, components/GlossaryItem/style.scss, components/Image/style.scss, package-lock.json, package.json
[![PR App][icn]][demo] | Fix CX-410
Stylelint was recently updated to include other necessary rules that
previously used to exist only in the main `readme` repo. Missing these
rules caused a style regression whereever `rgba` values were used with
percentages instead of decimals.
This should fix all background colors to have dimmed opacity as
intended.
=> chore(stylelint): upgrade to latest and fix all issues

example/demo.scss, example/index.html
Fixes rendering the ToC to the right, as well as loads in the main apps bundles.
=> fix: styles and toc

__tests__/flavored-compilers/code-tabs.test.js, processor/compile/code-tabs.js
| [![PR App][icn]][demo] | Fix CX-379 |
Prevent escaping asterisks in code tab names.
Not sure why the default code compiler escapes asterisks, but I don't see a reason for it. So I've added a custom compiler for code tabs to prevent this behavior.
=> fix: code tabs with *

__tests__/components/CodeTabs.test.jsx, index.js, lib/createElement/index.js
Fixes setting the theme on code tabs.
It appears that after a prior fix, we weren't setting the theme on CodeTabs. This resulted in a using a hack to set the theme in the main app.
=> fix(code-tabs): setting theme

__tests__/flavored-parsers/compact-headings.test.js, __tests__/flavored-parsers/utils.test.js, processor/parse/compact-headings.js, processor/parse/flavored/code-tabs.js, processor/parse/flavored/embed.js, processor/parse/gemoji-parser.js, processor/parse/magic-block-parser.js, processor/parse/utils.js, processor/parse/variable-parser.js
Fixes a very specific edge case with our compact headings:
```
##Heading
---
```
Should get render as:
```
<h2>Heading</h2>
<hr>
```
But would get render as:
```
<h2>##Heading</h2>
```
Also, to try and prevent this, does a little error checking when configuring the tokenizers.
=> fix: compact headings

.github/dependabot.yml
=> chore(dependabot): only notify on prod deps

__tests__/transformers/__snapshots__/table-cell-inline-code.test.js.snap, __tests__/transformers/table-cell-inline-code.test.js, index.js, processor/plugin/table-flattening.js, processor/transform/index.js, processor/transform/table-cell-inline-code.js
[![PR App][icn]][demo] | Fix RM-7646
This unescapes escaped pipe chars when rendering html. There appears to be a bug in remark or rehype where it displays the escaped pipe character in inline code spans within a table cell.
When using pipe characters in code spans within tables, you have to escape the pipe character, otherwise, it would result in additional table cells.
Consider the following markdown:
```
| td |
| -  |
| `echo \| cat` |
```
This would result in:
```
<table>
<thead>
<tr>
<td><code>echo \| cat</code></td>
</tr>
</thead>
</table>
```
Which doesn't seem like what was intended.
[icn]: …
=> feat: adds new transformer for inline code nodes inside table cells

__tests__/flavored-parsers/tables.test.js, processor/transform/table-cell-inline-code.js
| [![PR App][icn]][demo] | Fix CX-153 |
Fixes a case were having an empty (or invalid html) as children of a code tag crashed the process.
We have a custom plugin that escapes pipe characters (`|`) in code spans within tables, but it wasn't doing proper null checking.
=> fix: tables with invalid html

__tests__/flavored-compilers/break.test.js, __tests__/index.test.js, __tests__/normalize.test.js, index.js, options.js
Only normalize magic blocks at the root level.
In a previous PR, I removed the normalize option because it breaks magic block inside container elements. This broke a lot of pages that have magic blocks directly following other blocks. ie:
```
> needs to be normalized
[block:foo]{}[/block]
<div>also needs to be normalized</div>
[block:foo]{}[/block]
```
The problem is with how blocks are parsed. They usually allow for continuations. For example, blockquotes allow for some following lines to not start with the `>`. As a result, the magic blocks in the above example don't get matched by the magic block tokenizer, but are rather read in as inline content. We'd probably have to update all the `remark` tokenizers to be aware of the magic …
=> fix: normalize root level magic blocks

__tests__/flavored-compilers/reusable-content.test.js, __tests__/transformers/__snapshots__/reusable-content.test.js.snap, __tests__/transformers/reusable-content.test.js, processor/compile/reusable-content.js, processor/transform/reusable-content.js
| [![PR App][icn]][demo] | Part of RM-8041 |
| :--------------------: | :-------------: |
Updates the reusable content syntax to be just the tag name.
=> refactor: reusable content syntax

__tests__/__snapshots__/index.test.js.snap, components/Anchor.jsx
We don't need /reference-link in hub3 since everything is under /reference, so I updated the links generated to just be that instead since hub2 is dead!
=> chore: remove reference-link

__tests__/index.test.js, __tests__/transformers/reusable-content.test.js, index.js, options.js, processor/transform/reusable-content.js, scripts/perf-test.js
| [![PR App][icn]][demo] | Fix RM-8364 |
Add an option to **not** parse reusable content. Useful for nested editors.
=> feat: allow disabling reusable content

__tests__/flavored-compilers/reusable-content.test.js, __tests__/index.test.js, __tests__/transformers/reusable-content.test.js, index.js, options.js, processor/compile/reusable-content.js, processor/transform/reusable-content.js
Adds an option to write out resuable content as the content, instead of as the tag.
=> feat: write out reusable content as tags

__tests__/astToPlainText.test.js, __tests__/table-flattening/index.test.js, processor/plugin/table-flattening.js
| [![PR App][icn]][demo] | Fix RM-8651 |
Fixes table flattening of html tables.
The prior code had the expectation that it would only be flattening markdown tables, so it only looked at the first 2 children of a table. This PR iterates over **all** the children of a table, and cleans up the output string a little bit.
=> fix: table flattening

__tests__/flavored-compilers/reusable-content.test.js, __tests__/index.test.js, index.js, options.js, processor/compile/reusable-content.js, processor/transform/reusable-content.js
[![PR App][icn]][demo] | Fix RM-7812
A little more flexibility so reusable content can be passed as regular content (eg, for the TOC) 
=> fix: add conditional to reusable content transformer

.npmignore, package.json
[![PR App][icn]][demo] | Follow up to https://github.com/readmeio/markdown/pull/836
This repo has [a `files` array definition in the `package.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files) as well as a root-level `.npmignore`. The former mostly renders the latter useless, so I removed the latter. I also added the `npm-shrinkwrap.json` file to the `files` array so it will be properly published to the NPM registry.
To test this, you can run `npm pack` and you'll see a list of files that will be published. Note how `npm-shrinkwrap.json` now properly shows up in that list:
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488 …
=> fix: include shrinkwrap in npm output

example/Doc.tsx, index.tsx
Renaming `react` to `compile`
Doesn't make much sense to call it `react`.
=> refactor: rename react to compile

components/Image/style.scss
[![PR App][icn]][demo] | Fix RM-8544
We were determining whether `display: block` is applied to an image to center it based on the image has an `align` attribute with a value of `center`. The correct style doesn't get applied in Firefox since it uses `middle` in place of `center` for alignment values.
This PR just adds a CSS selector to target `align: middle` to make sure that images are aligned properly in Firefox as well.
=> fix: add css attribute selector for firefox

__tests__/flavored-parsers/__snapshots__/reusable-content.test.js.snap, __tests__/flavored-parsers/reusable-content.test.js, package-lock.json, processor/parse/reusable-content-parser.js
A recent PR introduced a regression where we could no longer parse RC within container blocks.
=> fix: dont require newline

__tests__/custom-components/index.test.tsx, example/Doc.tsx, example/docs.ts, index.tsx, package-lock.json, webpack.common.js, webpack.dev.js
Changes `rmdx.run` to be `async`.
I think use `mdx.runSync` means you can't call `import`?!
=> feat: async run

index.tsx, package.json
build and export typescript types. 
=> expose types

package-lock.json, package.json
| [![PR App][icn]][demo] | Fix RM-9354 |
Updates `@readme/emoji` to get a fresher set of emojis. 🤌 
=> feat: update emojis

__tests__/flavored-compilers/gemoji.test.js, __tests__/gemoji-parser.test.js, lib/owlmoji.js, processor/parse/gemoji-parser.js
| [![PR App][icn]][demo] | Fix RM-9702 |
Adds support for our legacy emoji syntax.
Previously, we swapped out our custom emoji library for a more standard one. Unrealized by me, our custom one used dashes instead of underscores. This checks if the same emoji name exists using underscores instead of dashes.
=> feat: support legacy gemoji

__tests__/transformers/readme-components.test.ts, enums.ts, index.tsx, package-lock.json, package.json, processor/transform/readme-components.ts, types.d.ts
Fixes a bunch of types from the jsx-coercion PR.
=> fix: types

processor/compile/embed.ts, processor/compile/html-block.ts, processor/compile/image.ts
[![PR App][icn]][demo] | Fix RM-9795 RM-9792
needed to adjust the output for the image & embed & html block compilers
=> fix: compilers

__tests__/compilers/callout.test.ts, processor/compile/callout.ts
| [![PR App][icn]][demo] | Fix RM-9785 |
Fixes saving callouts, again.
I had started copying a compiler from the source package. But I appear to have tried to reimplement the blockquote compiler, but incorrectly. This PR is much closer to the actual [block quote compiler](https://github.com/syntax-tree/mdast-util-to-markdown/blob/main/lib/handle/blockquote.js)
=> fix: callout breaks

__tests__/parsers/gemoji.test.ts, __tests__/transformers/readme-components.test.ts, enums.ts, example/Doc.tsx, processor/compile/image.ts, processor/transform/readme-components.ts
Fixes saving images. I mucked with the attributes and got it wrong. OOps.
=> fix: images

__tests__/compilers/compatability.test.ts, processor/compile/compatibility.ts
Fixes the term prop when saving mdx glossary itesm?!?!?!
=> fix: glossary

__tests__/Glossary.test.tsx, components/Glossary/index.tsx, components/Glossary/style.scss, package-lock.json, package.json
| [![PR App][icn]][demo] | Fix RM-9861 |
I changed the name of `GlossaryItem` to `Glossary`, but we never load `@readme/mdx`'s css in the main app. This caused the glossary tooltip to be unstyled.
I poked at getting rmdx's styles loaded, but ran into some issues with codemirror. So for now, I'm relying on the old styling to still be available, blheh.
=> style: fix glossary item

webpack.config.js
This allows the renderer to inject its own util module, which react-dom/server relies on for access to TextEncoder.
=> fix: add externals for node build

__tests__/transformers/readme-components.test.ts, __tests__/transformers/readme-to-mdx.test.ts, enums.ts, index.tsx, package-lock.json, package.json, processor/transform/index.ts, processor/transform/readme-components.ts, processor/transform/readme-to-mdx.ts, types.d.ts
| [![PR App][icn]][demo] | Fix RM-9868 |
Adds `tutorial-tile` to the readme mdx -> md layers.
This will allow saving Recipe's as JSX:
```
<Recipe id="..." {{ ... }} />
```
=> feat: translate recipes between mdx and md

__tests__/lib/hast.test.ts, index.tsx, lib/hast.ts, lib/index.ts, package-lock.json, package.json
| [![PR App][icn]][demo] | RM-9820 |
Adds a `htmlToHast` function.
This will be used in indexing,
```
mdx -> rmdx.run(rmdx.compile(mdx)) ->
react -> renderToSring(react) ->
html -> htmlToHast(html) ->
hast -> plain(hast) -> indexable plain text!
```
=> feat: add html to hast

__tests__/compilers/compatability.test.ts, processor/compile/compatibility.ts, processor/compile/index.ts
| [![PR App][icn]][demo] | RM-9897 |
Compiles `escape` nodes from rdmd.
In `remark@9`, they no longer treat escapes as a separate node type. This is mostly fine, except when we're migrating from rdmd to rmdx. The [rules for escapes](https://github.github.com/gfm/#backslash-escapes) seem pretty simple, so I'm not too worried about this change.
=> feat: escapes

components/Embed/index.tsx
[![PR App][icn]][demo] | Fix RM-10040
The hub was getting a flash of plain encoded HTML before the component decoded and rendered it. Hopefully this should solve that!
=> fix: decode HTML outside of component render

__tests__/compilers/html-block.test.ts, components/HTMLBlock/index.tsx, docs/html-tests.md, lib/run.tsx, processor/compile/html-block.ts, processor/transform/readme-components.ts, processor/utils.ts, types.d.ts
[![PR App][icn]][demo] | Fix RM-10043
Reworks HTML blocks a bit so they're nicer and easier for the user to interact with (makes sure the HTML is always nicely formatted for slate and the markdown/mdx doc)
=> fix: updates to html block

index.js
| 🎫 RM-9982 |
| :--------: |
For the most part, our sanitizer is automatically configured. But in certain instances– namely where we need to generate plaintext from a string of Markdown –it would errantly serialize `<style>` tag content.
Pass a list of tag names to force-strip them from the RDMD output. So to get rid of all style tags, you'd pass:
```js
rdmd.hast(body, { stripTags: ["style"] });
```
[Once this hits the monorepo][integration], customers should no longer see weird looking meta excerpts for their docs in Google.
[integration]: https://github.com/readmeio/readme/pull/12167
=> feat: new `stripTags` option

components/Code/style.scss
Jaclyn and I noticed that the font size for code blocks was a little small:
So this PR bumps it to `95%`
`beta` PR #912
=> style: bump code font size

components/Code/style.scss
Jaclyn and I noticed that the font size for code blocks was a little small:
So this PR bumps it to `95%`
`next` PR #915
=> style: increase code font size

processor/transform/variables.ts
| [![PR App][icn]][demo] | RM-9917 |
Adds the position data to variable nodes, oops.
Useful in the editor.
=> feat: mdx position

__tests__/browser/markdown.test.js, __tests__/compilers/html-block.test.ts, __tests__/lib/mdast.test.ts, __tests__/transformers/readme-components.test.ts, __tests__/transformers/variables.test.tsx, lib/ast-processor.ts, lib/compile.ts, processor/compile/variable.ts, processor/transform/code-tabs.ts, processor/transform/index.ts, processor/transform/readme-components.ts, processor/transform/variables.ts, types.d.ts
| [![PR App][icn]][demo] | RM-9917 |
Adds `readme-variable` to the mdast for the editor to consume
I found myself transforming `mdx` nodes in the editor and decided I should stick my existing convetion to do that in the library.
=> feat: readme-variable

__tests__/transformers/embeds.test.ts, __tests__/transformers/images.test.ts, components/Image/index.tsx, processor/transform/images.ts, processor/transform/inject-components.ts, processor/transform/readme-components.ts, types.d.ts
[![PR App][icn]][demo] | Fix RM-10049
cleaner way to add/update image caption
=> fix: add image component caption as children

__tests__/compilers/compatability.test.ts, processor/compile/compatibility.ts, processor/compile/index.ts, processor/utils.ts
[![PR App][icn]][demo] | Fix RM-10134
Converts the rdmd-style `mdast` for the image and embed blocks to the new MDX components
=> feat: compatibility for rdmd image/embed components

index.js
| 🔥 [Channel] | ✅ Approved as #920 |
| :----------: | :----------------: |
Because of [how we model empty `variableDefaults` in the project schema](https://github.com/readmeio/readme/blob/5f0a0c3768b2cb3f745cdb0ffb696a49e614c5c5/packages/models/project/index.js#L684-L706), these arrays were being passed to RDMD as `[null]` instead of `null`.
Hard to test until this hits the monorepo, but once it does we should be on the lookout for [this error](https://readme.sentry.io/issues/5549356424/?project=2052166&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&stream_index=0).
[channel]: https://readmeio.slack.com/archives/C07ACJ61A6Q
=> fix: handle null variable defaults

__tests__/astToPlainText.test.js, index.js, processor/plugin/plain-text.js
| 📖 [PR App][demo] |
| :---------------: |
Magic HTML blocks were being entirely skipped when serializing to plain text.
Pull down this branch and try running the following snippet. If the HTML block serializes to plain text nicely (instead of giving back a blank string) this worked! :tada:
```js
const docBody = '[block:html]{ "html": "<p>Lorem <b>ipsum</b> dolor sit amet, consectetur adipiscing elit.</p>" }[/block]\n\n> 👍 title\n> complex|multi\n> ---|---\n> child|body';
const output = rdmd.astToPlainText(rdmd.hast(docBody));
```
Now give the `astToPlainText()` unit tests a whirl. If everything comes up green, we're good! 🤘
```
npx jest --watch -- astToPlainText.test.js
```
[#914]: …
=> chore(astToPlainText): processor improvements

.github/workflows/bundlewatch.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
- update github actions versions. The v3 of a bunch of these actions is deprecated.
I noticed these deprecated actions when working with Jenn yesterday. Nothing urgent at all, just bumping them for safety.
=> chore(gha): update github actions versions

processor/plugin/toc.ts
| 💬 [Thread] |
| :---------: |
[thread]: https://readmeio.slack.com/archives/C04R9PADCS3/p1720026196603799?thread_ts=1720025418.443289&cid=C04R9PADCS3
=> fix(beta): toc generation when using MDX components

lib/ast-processor.ts, lib/hast.ts
| [![PR App][icn]][demo] | RM-9815 |
Adds an option for remark plugins.
By adding the `remarkPlugins` option, I can write a small plugin to support indexing in the main app. We recently decided we're going to refocus this repo to only deal with converting MDX to React. Recently, we've been adding a lot of code that is specific only to our editor, and we'd like to move that someplace.
The problem I'm trying to solve is for indexing. When converting `mdast` to `hast`, in MDX, we lose some information. `remark-rehype` doesn't know what to do with `mdxJsxFlowElements` and replaces them with `div`'s.
**mdx**
```mdx
<h2>Hello, world!</h2>
```
**mdast**
```json
{
"type": "root",
"children": [
{
"type": "mdxJsxFlowElement",
"name": "h2",
"children": [
{ …
```
=> feat: remark plugins

__tests__/compilers/tables.test.js, processor/transform/tables-to-jsx.ts
| [![PR App][icn]][demo] | RM-9793 |
Skips the align attrs if they're all null.
I didn't realize markdown tables default to null, rather than a string:
```
| foo |
| --- |
```
=> fix: skip null align

.github/workflows/ci.yml, __tests__/compilers/tables.test.js, processor/transform/tables-to-jsx.ts
| [![PR App][icn]][demo] | RM-9793 |
Fixes saving 'complex' tables.
In a prior PR, I added a new node type `tableau` to represent tables with block content. This mostly worked for the editor, but not when doing `mdx(mdast(doc))`. This PR adds a transformer, so the a `tableau` is converted to a JSX table just like regular `table`'s.
This also adds the check so, if a `tableau` no longer has block content, it's saved as markdown!
Hard to test outside the main app.
=> fix: saving tables

__tests__/compilers/tables.test.js, processor/transform/tables-to-jsx.ts
| [![PR App][icn]][demo] | RM-9793 |
Fixes saving lists (other blocks too) in table headers.
Kind of hard to test outside the editor. But I've been testing by running `make mdx` and playing around in the styleguidist playground thingy.
=> fix: lists in table headers

README.md, __tests__/lib/tags.test.ts, index.tsx, lib/index.ts, lib/tags.ts
| [![PR App][icn]][demo] | RM-10502 |
| :--------------------: | :------: |
Adds the `tags` export.
`tags` will return a list of custom tags in the document.
=> feat: tags

__tests__/fixtures/image-block-no-attrs.mdx, __tests__/transformers/images.test.ts, package-lock.json, package.json, processor/transform/readme-to-mdx.ts
| 🎫 Fixes RM-10621 |
| :---------------: |
Pull this branch down and try running [the new test in the `images.test.ts` file](https://github.com/readmeio/markdown/pull/952/files#diff-9b10647639421f1135101ae63ca87780ab63af9e81c8da0b00ea6d0ddd08b8b6R26-R50).
=> fix(img): set src properly for magic image blocks

components/Tabs/style.scss
- use project color primary for tabs
=> chore: tabs component color

components/Image/style.scss
| [![PR App][icn]][demo] | Fix CX-1018 |
Fixes some image styling by pulling in the styles from pre-mdx
Testing locally is pretty convoluted. Probably easier to test in the main app.
=> fix: image styles

__tests__/compilers/compatability.test.ts, __tests__/compilers/images.test.ts, processor/utils.ts
| [![PR App][icn]][demo] | RM-10691 |
| :--------------------: | :------: |
Fixes compiling images.
The problem was our naive transformer that could not handle non string attributes. For instance, using a `false` value would crash the compiler:
```
<Image border={false} />
```
This updates the `toAttributes` method to create the valid AST.
Do the tests pass?
You could test it locally like:
```
npm i && npm run build
node
> const rmdx = require('./')
> rmdx.mdx(rmdx.mdast('<Image border={false} />'))
```
But that's roughly the same as the tests?
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b …
=> fix: image compiling

components/Accordion/index.tsx, components/Accordion/style.scss, components/Tabs/index.tsx, components/Tabs/style.scss
[![PR App][icn]][demo] | Fix RM-10694
- Add `icon` and `iconColor` props to <Tab>
- Replace default marker with icon in <Accordion>
=> chore: update tabs & accordions ui

__tests__/compilers/images.test.ts, processor/utils.ts
| [![PR App][icn]][demo] | RM-10062 |
| :--------------------: | :------: |
Fixes parsing `undefined` attributes.
=> fix: undefined check

README.md, lib/mdx.ts
[![PR App][icn]][demo] | RM-10779
Allows passing through options to `remark-stringify`. 
There are places in the main app where we'd like to be able control the formatting of mdx. 
=> feat: pass through stringify options

__tests__/compilers/compatability.test.tsx, __tests__/compilers/images.test.ts, __tests__/fixtures/image-block-no-attrs.mdx, __tests__/helpers.ts, __tests__/index.test.js, __tests__/lib/mdast/null-attributes/in.mdx, __tests__/lib/mdast/null-attributes/out.json, __tests__/lib/plain.test.ts, __tests__/transformers/images.test.ts, processor/transform/images.ts, processor/transform/readme-components.ts, processor/transform/readme-to-mdx.ts, processor/utils.ts, types.d.ts
[![PR App][icn]][demo] | Ref RM-10799, RM-10667
Fixes some issues when migrating images.
- `mdast` was sometimes not correctly populating image attributes. I tried to make it more normal, so the attributes are copied to both the node and the hProperties. :shrug:
- a `null` attribute could crash the transormers. I've added a null check, as well as filtered out empty attributes.
This should probably be tested in the main app so we get the full integrations.
=> fix: image migration issues

__tests__/compilers/gemoji.test.ts, processor/transform/readme-to-mdx.ts
[![PR App][icn]][demo] | Ref RM-10740
:-------------------:|---
Compiles 'owlmoji' (:owlbert:) back to shortcodes.
I noticed while investigating frozen properties, that we weren't saving owlmoji's back to shortcodes.
=> fix: compiling emoji

__tests__/compilers/compatability.test.tsx, processor/transform/readme-to-mdx.ts, types.d.ts
[![PR App][icn]][demo] | RM-10929
Fixes migrating images with captions.
Recent PRs have been normalizing the use of `src` and `url` with the various image transformers. I misssed one 🤮
=> fix: migrating captions

__tests__/compilers/compatability.test.tsx, processor/transform/tables-to-jsx.ts
[![PR App][icn]][demo] | Ref CX-1112
Fixes breaks in magic block tables.
=> fix: migrating magic block tables with breaks

__tests__/compilers/compatability.test.tsx, processor/compile/callout.ts
[![PR App][icn]][demo] | Ref CX-1067
Fixes migrating callouts with no title.
I completely missed the fact that RDMD callouts use `title` and `value` for rendering. The new MDX transformers just use `children`. Oops!
=> fix: migrating callouts

__tests__/compilers/compatability.test.tsx, __tests__/transformers/images.test.ts, processor/compile/compatibility.ts, processor/transform/readme-to-mdx.ts
[![PR App][icn]][demo] | Ref CX-1110
Fixes migrating image borders.
Yet-another-image-prop we missed. I wasn't aware that magic block images were only storing the `border` as a className in the ast. Oops.
After the migration, it _should_ only be stored as an attribute on an `image-block` node.
=> fix: migrating image borders

__tests__/compilers/compatability.test.tsx, processor/transform/tables-to-jsx.ts
[![PR App][icn]][demo] | Ref RM-10616
Fixes migrating tables with inline code with newlines.
Our previous check for converting markdown tables to JSX only scanned text nodes. That would skip inline code and inline html. Uh oh.
=> fix: tables with inline code with newlines

__tests__/plugins/toc.test.tsx, processor/plugin/toc.ts
[![PR App][icn]][demo] | Ref RM-10928
Prevents rendering markdown in the ToC
=> fix: dont render markdown in toc

components/Code/style.scss
=> fix: copy button icons

__tests__/compilers/compatability.test.tsx, processor/transform/compatability.ts
[![PR App][icn]][demo] | Ref CX-1113, CX-1114
Fixes migrating images with legacy data.
We deprecated a particular format of image magic block, but we failed to ever migrate pages away from it. They've been broken/changed for awhile, and I'm not sure if we could correctly detect the format at this point?
When they get parsed into an AST, they appear to be inline image nodes, which can then compile incorrectly. We've been treating image nodes that are alone in a paragraph as block images for awhile, so lets encode that in the migration.
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee …
=> fix: legacy image migration

components/Accordion/index.tsx, components/Accordion/style.scss
- Render accordion toggle fa icon correctly (reverted from this [change](https://github.com/readmeio/markdown/pull/969/files#diff-909b2e4084c67e1c9a9d120d5421457bc8d4bd0d822396205a76e4eff3439841))
=> fix: accordion toggle icon

__tests__/compilers/compatability.test.tsx, processor/transform/compatability.ts
[![PR App][icn]][demo] | Ref CX-1135
Attempts to migrate more buggy emphasis syntax.
=> feat: fix incompatable emphasis

components/Code/index.tsx, example/Doc.tsx, example/Form.tsx, lib/compile.ts, processor/transform/code-tabs.ts, processor/transform/index.ts
| 🎫 Resolves RM-10635 | 🐙 Closes #964 |
| :------------------: | :------------: |
The main `RMDX.compile()` method should respect the `copyButtons` param when rendering our code block components.
https://github.com/readmeio/markdown/blob/96f9644f04e6d8e3ffff6f9c014432f901c0b804/lib/compile.ts#L28
Pull this PR down, run the `start` script, and [navigate to the “Code Blocks” example](http://localhost:9966/#/codeBlockTests?copyButtons=true "View local dev playground→"). Try hovering over a code block to verify that the copy button is only shown if/when the <kbd>**Copy Buttons**</kbd> toggle is checked.
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.sv …
=> fix: respect the top-level `copyButtons` option

components/Image/style.scss
| :ticket: Fix RM-11105, RM-11116 |
| :-----------------------------: |
Checkout the `style/image/match-new-alignment-selectors` branch, run `start`, and open up [this example in the playground][local]. Try switching the `<Image[align]>` prop from "left" to "center" to "right". If it’s reflected correctly in the right-side render, this worked! :tada:
[local]: http://localhost:9966/#/edited?edit=%3CImage+align%3D%22right%22+width%3D%2250%25+%22+src%3D%22https%3A%2F%2Fmedia.istockphoto.com%2Fid%2F589125884%2Fphoto%2Fman-eating-pizza-and-making-an-ok-gesture.jpg%3Fs%3D170667a%26w%3D0%26k%3D20%26c%3DcGTsJbWLAYyOjev9zFhWp6iYX-p39qsrvTEsF699NfI%3D%22+%2F%3E%0A%0ALorem+ipsum+odor+amet%2C+consectetuer+adipiscing+elit.+Blandit+morbi+fames+quisque+mattis+tellus+augue.+Torquent+conubia+enim+malesuada …
=> style(Image): match new alignment selectors

__tests__/compilers/compatability.test.tsx, processor/compile/compatibility.ts
Don't attempt to migrate inline html tags.
1. `remark` only parses the tags, so something like:
```
<span>OH no!</span>
```
becomes:
```
<span />OH no!<span />
```
2. This will prevent migrating custom inline tags as a side effect.
This shouldn't effect production code directly, only the migration. I think it's best to test directly in the migration?
=> fix: better tag handling

package-lock.json, package.json, webpack.common.js
Replace `node-sass` with `dart-sass` (`sass`).
`node-sass` started failing to build on the github action runners. Eek! I guess it's time to chuck it. :wave:
=> chore: replace node-sass

webpack.config.js
Configures webpack to externalize `mermaid`
=> fix: externalize mermaid

__tests__/migration/emphasis.test.ts, processor/migration/emphasis.ts
[![PR App][icn]][demo] | Ref CX-1238
Fixes emphasis with links in it.
The original implementation of this was naively assuming there would only be one child node. Ope.
=> fix: emphasis with links

__tests__/migration/tables.test.ts, processor/migration/table-cell.ts
[![PR App][icn]][demo] | CX-1153
Fixes a regression when migrating tables with emphasis.
The context for this is a bit long, but here's a summary:
1. magic block tables permitted block content
2. gfm tables did not
3. we dropped support for block content because the magic block implementation was problematic
4. users really want block content in tables, so we allowed breaks, `\n`
5. somewhere a long the line, the editor mucked up list like syntax in tables
6. I added a regex to look for that instance and correct it for the migration
7. that regex was not careful enough, and started matching emphasis
8. this PR fixes that to better not-match emphasis
[demo]: …
=> fix: bold in tables

__tests__/migration/tables.test.ts, processor/migration/table-cell.ts
[![PR App][icn]][demo] | CX-1192
Fixes migrating tables with html.
We're doing some shenanigans with table cells so that they support block content. We basically reparse each cell as if it's a root markdown doc and then re-insert it into the tree.
This adds block level html as a condition for wrapping said content in a paragraph. Wrapping it in a paragraph seems to be required to get remark to compile newlines correctly. :shrug:
=> fix: migrate tables with html

__tests__/compilers/compatability.test.tsx, __tests__/migration/emphasis.test.ts, __tests__/migration/html-comments.test.ts, __tests__/migration/html-entities.test.ts, __tests__/migration/image.test.ts, __tests__/migration/link-reference.test.ts, __tests__/migration/magic-block.test.ts, __tests__/migration/tables.test.ts, index.tsx, lib/index.ts, lib/migrate.ts
[![PR App][icn]][demo] | Ref RM-11191
Adds a `migrate` export and moves a `replaceAll` into this repo.
=> feat: migrate export

package-lock.json, package.json
Installing the markdown package throws these warnings from NPM for the `trim` package:
```
npm warn deprecated trim@1.0.1: Use String.prototype.trim() instead
npm warn deprecated trim@0.0.1: Use String.prototype.trim() instead
npm warn deprecated trim@0.0.1: Use String.prototype.trim() instead
```
It seems that we're no longer using `trim` anymore(?) so I'm removing it from being a dependency.
```
> npm ls trim
@readme/markdown@7.9.0
├─┬ @readme/markdown-legacy@npm:@readme/markdown@6.87.1
│ └─┬ remark-parse@8.0.3
│   └── trim@0.0.1
└── trim@1.0.1
```
```
@readme/markdown@7.9.0
└─┬ @readme/markdown-legacy@npm:@readme/markdown@6.87.1
└─┬ remark-parse@8.0.3
└── trim@0.0.1
```
All tests were still passing and the dist still gets built fine with …
=> fix: removing our dependency on `trim`

__tests__/compilers/compatability.test.tsx, __tests__/helpers.ts, __tests__/migration/emphasis.test.ts, __tests__/migration/html-comments.test.ts, __tests__/migration/html-entities.test.ts, __tests__/migration/image.test.ts, __tests__/migration/link-reference.test.ts, __tests__/migration/magic-block.test.ts, __tests__/migration/tables.test.ts, lib/mdastV6.ts, lib/migrate.ts, package-lock.json, package.json, processor/migration/table-cell.ts, webpack.config.js
Requires passing `rdmd` in as an option to the migration.
Bundling `@readme/markdown@v6.87.1` was doubling the time it takes it import the dist. This can be a problem in `mdx-renderer` which does this with every request.
=> fix: dont bundle rdmd

webpack.config.js
Don't externalize `mermaid` for the node build.
In `mdx-renderer` it's dynamically imported, so it doesn't usually get executed. If we externalize it, we either have to specifically include it in the execution environment, or configure rollup to inline it. The former is an unnecessary hassle, and the latter appears to execute the code immediatelly and slow down the build. So lets go back to bundling it, but dynamically importing it.
=> fix: dont externalize mermaid

__tests__/lib/plain/custom-components.test.ts, lib/hast.ts, lib/plain.ts, processor/transform/index.ts, processor/transform/mdx-to-hast.ts
[![PR App][icn]][demo] | Ref RM-11201
Adds the `title` prop from our built ins to `plain`
This will make content in the `title` indexable in the main app.
=> feat: add title props to plain

__tests__/migration/tables.test.ts, processor/migration/index.ts, processor/transform/tables-to-jsx.ts
[![PR App][icn]][demo] | Ref CX-1610
Fixes migrating tables with leading escapes.
The `phrasing` util is not aware of the `escape` node type, as it is from a previous version of `mdast`. This was confusing our `tables-to-jsx` transformer. It would look at tables and decide if it could be compiled to markdown format, eg:
```
| a | b |
|---|---|
| 1 | 2 |
```
or if it should be compiled to JSX format, eg:
```jsx
<Table>
<TableHead>
<TableRow>
<TableCell>a</TableCell>
<TableCell>b</TableCell>
</TableRow>
</TableHead>
<TableBody>
<TableRow>
<TableCell>1</TableCell>
<TableCell>2</TableCell>
</TableRow>
</TableBody>
</Table>
```
[prod]: …
=> fix: dont treat escapes as flow

__tests__/variables/index.test.tsx, contexts/index.tsx, lib/compile.ts, lib/run.tsx, utils/user.ts
[![PR App][icn]][demo] | Fix RM-11562
Allows user variables in esm code.
Prior to this, user variables (eg `{user.email}`) were being replaced with a JSX component (`<Variable name="email" />`) opaquely. The actual values were provided by the `VariableContext`. This mimiced how they were handled in pre-mdx versions of the library. This PR undoes that, and provides the `user` object as a top level import. The following was not possible before, but is possible now:
```
export const HelloWorld = () => {
return <div>{user.email}</div>
}
```
We had talked about implementing it this way, and I somehow ignored/forgot that. Oops.
***
The `VariableContext` is still being used, because our custom wrapper around code blocks will also insert the `user` object into …
=> feat: global vars

__tests__/lib/exports/index.test.ts, __tests__/lib/exports/input/multipleExports.mdx, __tests__/lib/exports/input/singleExport.mdx, __tests__/lib/exports/input/weirdExports.mdx, __tests__/lib/hast.test.ts, __tests__/lib/mdast/__snapshots__/index.test.ts.snap, __tests__/lib/mdast/esm/in.mdx, __tests__/lib/mdast/esm/out.json, __tests__/lib/mdast/index.test.ts, lib/exports.ts, lib/index.ts, lib/tags.ts, processor/utils.ts
- Adds a util for parsing out the export names from an MDX string 
- Adds tests for a few different cases
=> chore: add exports util with tests

__tests__/migration/html-blocks.test.ts, processor/compile/compatibility.ts, processor/transform/readme-to-mdx.ts, processor/utils.ts
| [![PR App][icn]][demo] | Ref CX-1712|
Fixes an issue with the migration were html blocks contain backticks were not being escaped. This would be a parsing error at runtime.
=> fix: migrating html with backticks

index.tsx
- I forgot to actually export the new `exports` util oops 
=> chore: add missing export

components/Cards/style.scss
[![PR App][icn]][demo] | Fix CX-1683
- set cards to one column on mobile
=> fix: make cards responsive

__tests__/lib/run.test.tsx, lib/run.tsx
| [![PR App][icn]][demo] | Fix RM-11562 |
| :--------------------: | :----------: |
Fixes user variables in the mdx-renderer.
The mdx-renderer passes in `{ imports: { React } }` as they have to provide their own compiled version. `lib/run` was not properly merging that with it's own imports, and that was causing `user` to be undefined!
=> fix: imports

__tests__/lib/exports/index.test.ts, __tests__/lib/exports/input/weirdExports.mdx, lib/exports.ts
[![PR App][icn]][demo] | Fix RM-11826
I realized that the previous implementation did not capture multiple exports if they were separated by only a single newline `\n`. 
- refactors `exports` to traverse into each `mdxjsEsm` node and look for each type of declared export declaration: `VariableDeclaration, FunctionDeclaration, ClassDeclaration`
- updates test cases
=> fix: refactor exports util to support broader formatting and export types

README.md
Noticed our README format was pretty out of date with how our other OSS projects (like [oas](https://npm.im/oas) or [rdme](https://npm.im/rdme)) look these days so I've reformatted its header to be more in line with those.
=> docs: reformatting our README a touch in line with our other OSS projects

__tests__/custom-components/index.test.tsx, lib/run.tsx
| [![PR App][icn]][demo] | Ref RM-11968 |
| :--------------------: | :-: |
Passes through props to the default components.
Prior to this, we were ignoring any props that we're being passed to the default exports, oops!
=> fix: pass through props

__tests__/transformers/tailwind.test.tsx, components/TailwindRoot/index.tsx, example/Doc.tsx, lib/compile.ts, processor/transform/tailwind.tsx, utils/consts.ts, utils/tailwind-bundle.ts
| [![PR App][icn]][demo] | Ref RM-12063 |
| :--------------------: | :----------: |
Allows parsing the root doc for tailwind styles.
If you pass `{ useTailwind: true, useTailwindRoot: true }` to `compile` it will parse the root document as well as the components for tailwind styles. It will be up to the consumer to add the `.tailwind-root` class to the root div though.
=> feat: allow parsing root doc for styles

styles/gfm.scss
[![PR App][icn]][demo] | Fix CX-1800
- We weren't overriding the `margin-top` of the first element in superhub pages because of the `<style>` tag
- Does this selector make the most sense ?
=> fix: margin on style tag

components/TailwindStyle/index.tsx, example/Doc.tsx
| [![PR App][icn]][demo] | Ref RM-12182, RM-12042 |
| :--------------------: | :--------------------: |
Updates `TailwindStyle` to work in a shadow root.
This PR reworks the `TailwindStyle` component to not push styles into the `head`. It also adds back generating the stylesheet on load, as the timing appears to be different in the main app than the demo.
I haven't been able to get `npm link` to work recently. Copying the dist might, but I was getting build errors, so I wasn't confident that it was working properly.
That being said, I copied the `TailwindStyle` component directly into the app to dev and test.
[icn]: …
=> fix: loading styles in a shadow-dom

components/Callout/index.tsx, components/Code/index.tsx, components/CodeTabs/index.tsx, contexts/Theme.ts, contexts/index.tsx, lib/run.tsx
[![PR App][icn]][demo] | Fix RM-12348
We weren't including the `theme` in `RunOpts`, and no props are being exclusively passed in to the components. This meant Mermaid Diagrams would always fallback to the `default` theme and not appropriately match the project theme. 
I added a `ThemeContext` through which we can set and access the project theme that's passed in via the `RunOpts`.
Note: I can't figure out how to test these changes locally linked with the `readme` repo 😭 . Without sinking too much time in it, may just want to try to get this published in order to test via `readme`. 
[icn]: …
=> fix: pass through theme prop to CodeTabs from RunOpts

contexts/index.tsx, lib/run.tsx
[![PR App][icn]][demo] | Fix RM-12348
We had hoped to not need to re-run the run function when the theme changes, but in order to accurately toggle the theme of our components (Mermaid diagrams, in this case), we need to pass the theme as a `RunOpts` prop. 
https://github.com/user-attachments/assets/d8ef110f-a6f3-4e57-a578-89fc0d23809d
=> fix: pass theme via runopts

styles/gfm.scss
[![PR App][icn]][demo] | Fix RM-12490, [Thread](https://readmeio.slack.com/archives/C089VLEECKC/p1744905351133679)
before we were setting `margin-top: 0` to the 2nd child element in a page, which should have been the first markdown element after the `<style>` tag but we have since then added another `<style>`
this updates the selector to target the first child element that is _not_ a `<style>` ([TIL](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child#the_of_selector_syntax))
should look like this:
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d …
=> fix: margin element selector

components/Code/index.tsx, contexts/CodeOpts.ts, contexts/index.tsx, lib/run.tsx
[![PR App][icn]][demo] | Fix CX-1879
- Enable passing in `CopyButton` prop for code blocks
=> fix: missing code copy

components/HTMLBlock/index.tsx, package-lock.json, package.json, webpack.config.js
Externalizes `@readme/syntax-highlighter` and `acorn`.
Those deps are duplicated across the main readme app, and definitely do not need to be bundled.
It also removes an import of `react-dom/server` which seems fairly extraneous. The `HTMLBlock` component was checking if you passed in react components as children, and converting them to a string. I don't think that's something we should support.
**Before** (parsed size of 4.05MB)
**After** (parsed size of 2.5MB)
=> feat: external large deps

package-lock.json
[![PR App][icn]][demo] | |
This upgrades some of the vulnerable NPM dependencies and takes the project from:
```
34 vulnerabilities (3 low, 10 moderate, 21 high)
```
To:
```
16 vulnerabilities (1 moderate, 15 high)
```
Package upgrades include:
- @babel/* packages: Upgraded from various 7.23–7.26.x versions to 7.27.x.
- @esbuild/* and esbuild: Upgraded from 0.20.2 to 0.25.4 (and all platform-specific binaries).
- @octokit/*: endpoint, openapi-types, plugin-paginate-rest, request, request-error, types all upgraded to newer major/minor versions.
- @rollup/* and rollup: Upgraded from 4.14.2 to 4.40.2 (and all platform-specific binaries).
- @vitejs/plugin-react: 4.2.1 → 4.4.1.
- vite: 5.2.8 → 6.3.5.
- axios: 1.7.7 → 1.9.0.
- body-parser: 1.20.2 → 1.20.3.
- …
=> chore(deps): upgrade some security vulnerabilities

components/Embed/index.tsx
[![PR App][icn]][demo] | Fix CX-1935
- Add `title` prop to `iframe` component for a11y requirements
=> fix: missing iframe title

__tests__/lib/__snapshots__/owlmoji.test.ts.snap, __tests__/lib/owlmoji.test.ts, lib/owlmoji.ts
In https://github.com/readmeio/markdown/pull/1114 I added parity for @readme/mdx to expose full emoji list like we do in the legacy package. 
But I noticed pulling this into the UI that the emoji list is sorted differently:
| Before (uses `@readme/markdown`) | After (uses `@readme/mdx`) |
| --- | --- |
| <img width="375" alt="image" src="https://github.com/user-attachments/assets/f939387d-a73b-4eca-b91b-37d0c453a6d6" /> | <img width="372" alt="image" src="https://github.com/user-attachments/assets/18bd898c-59f9-4088-8e47-5b0f68ea815e" /> |
I'd changed this line
https://github.com/readmeio/markdown/blob/f369acff29394bc0cc172a9d0ffc918ac478960e/lib/owlmoji.js#L48
to use `localCompare` …
=> fix: remove owlmoji collection sorting, add unit tests

__tests__/compilers/plain.test.ts, enums.ts, package.json, processor/compile/index.ts, processor/compile/plain.ts, types.d.ts
| [![PR App][icn]][demo] | Fix RM-12842 |
Adds a plain compiler for avoiding markdown escaping during compilation.
=> feat: plain compiler

__tests__/transformers/readme-components.test.ts, processor/compile/compatibility.ts, processor/transform/readme-components.ts
[![PR App][icn]][demo] | Fix RM-12670
In an effort to simplify the Editor blocks, we're transitioning the `Glossary` term from having a special UI to being displayed as plain MDX. 
This removes the logic that transforms `<Glossary>` mdx tags into a special node type. 
=> feat: remove glossary as special block

__tests__/compilers/callout.test.ts, __tests__/transformers/callouts.test.ts, processor/transform/callouts.ts, processor/transform/readme-components.ts, processor/transform/readme-to-mdx.ts
| [![PR App][icn]][demo] | Ref RM-12848 |
| :--------------------: | :----------: |
Updates the callout transformers to better default to markdown.
- Allows a JSX `Callout` to only define a theme or an icon.
- Saves a callout to markdown when only an icon is defined. This is the default behavior from the editor.
=> feat: better callout defaults

components/Mermaid/index.tsx, components/Mermaid/style.scss, components/index.ts, docs/mermaid.md
[![PR App][icn]][demo] | Fix RM-12974
Support rendering mermaid as a JSX `<Mermaid>` component
=> feat: jsx mermaid

__tests__/components/test.js, components/Tooltip/index.jsx, jest.setup.js
[![PR App][icn]][demo] | Fix CX-2117
#1174 introduced the use of `crypto.randomUUID` which isn't available in `markdown-legacy`'s runtime env. Error revealed when trying to bump the version in the main app:
=> fix: remove use of `crypto.randomUUID`

components/Tooltip/index.jsx
[![PR App][icn]][demo] | Fix CX-2117
A last attempt to solve [the issue described in this thread](https://linear.app/readme-io/issue/CX-2117/glossary-popup-not-appearing-in-translated-pages#comment-6ab2666a). Maybe something about client and server hydration mismatches is the cause?
=> fix: try adding tooltip check for client

__tests__/lib/compile.test.ts, lib/compile.ts, package-lock.json, package.json
Fixes sanitization of readme style protocol links `[label](doc:slug)`.
We recently switched our plain markdown parsing to use the latest version of this package with `{ format: 'md' }`. We want to eventually remove `@readme/markdown@6`, but it also helped reduce our bundle size. In the process, we failed to port over our custom sanitization schema. For the most part, I think this is fine to drop support for old, custom markdown features. But it does break our custom protocol links, which at least one enterprise customer was using.
[icn]: …
=> fix: readme protocol links

components/CodeTabs/style.scss, components/Tabs/style.scss, example/styles/theme.scss
Adds focus state to code tabs.
=> fix: adds focus outline to code tabs
