readmeio/markdown

components/HTMLBlock.jsx
=> fix: compat mode in ssr

__mocks__/.eslintrc, __mocks__/copy-to-clipboard.js, __tests__/components/Code.test.jsx, components/Code/index.jsx, package-lock.json, package.json
The Code component uses the syntax-highlighter for variable
interpolation, but it was passing the uninterpolated text to the copy
function.
=> fix(code): copying interpolated variables

components/HTMLBlock.jsx
This reverts commit 64f11350402377e78dbe75e66615803be4ec76e6.
=> Revert "fix: compat mode in ssr (#74)"

package-lock.json, package.json
Adds codemirror as explicit dev dependency.
=> fix: add codemirror as exp dep

package-lock.json, package.json, webpack.config.js
This sets `@readme/variable` as a peerDep. Variable is using a context
to propagate user variables. So, it needs to be a singleton in the app,
otherwise any imported consumers won't be matched the correct provider.
[ticket](https://app.asana.com/0/1199089258199423/1199528380076880/f)
=> chore(deps): move variable to peerDep

__tests__/components/HTMLBlock.test.jsx, docs/code-blocks.md, package-lock.json, package.json
See https://github.com/readmeio/syntax-highlighter/pull/105 for unit tests
=> feat: adding support for highlighting OCaml and R languages

index.js, webpack.config.js
Exports Components. Changes the library type to `umd`?
=> feat: export components

components/Heading/index.jsx
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes RM-1552
:---:|:---:
- Add aria-label to anchors 
- Does aria-label get applied correctly to anchor links?
[demo]: https://markdown-pr-230.herokuapp.com
[prod]: https://docs.readme.com/docs/overview-redesigned-api-reference
=> fix(heading): add aria-label to anchors

__tests__/flavored-compilers.test.js, processor/compile/var.js
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes CX-400
:---:|:---:
Fixes the variable compiler to output the original text
Co-authored-by: Julia Hotaling <42787244+julshotal@users.noreply.github.com>
=> fix: variable stringification

__tests__/__snapshots__/index.test.js.snap, __tests__/index.test.js
[<img height=20 src=https://readme.com/static/favicon.ico align=center>][demo] | Fixes RM-1571
:---:|:---:
- Test if aria-label is being applied correctly — Related to this [PR](https://github.com/readmeio/markdown/pull/230)
Does the snapshot of the heading component look as expected?
[demo]: https://markdown-pr-234.herokuapp.com
[prod]: https://developers.readme.io
=> test(heading): add test for aria-labels being passed properly

__tests__/__snapshots__/flavored-compilers.test.js.snap, __tests__/__snapshots__/magic-block-parser.test.js.snap, __tests__/flavored-compilers.test.js, __tests__/magic-block-parser.test.js, package.json, processor/compile/div.js
RM-3058 |
:---:|
Compiles custom magic blocks!
=> feat: compile custom magic blocks

__tests__/variable-parser.test.js, package-lock.json, package.json
[<img height=20 src=https://readme.com/static/favicon.ico align=center> Demo App][demo] | 
:---:
=> chore(devDeps): update @readme/variable to 13.6.5

__tests__/variable-parser.test.js, package-lock.json
[<img height=20 src=https://readme.com/static/favicon.ico align=center> PR App][demo]
:---:
[demo]: https://markdown-pr-424.herokuapp.com
=> chore(deps-dev): update @readme/variable to v13.6.6

.github/dependabot.yml
Ignores aren't being configured properly in the Dependabot config.
=> ci: fixing the dependabot config

components/HTMLBlock/index.jsx
I'm struggling to debug html block re-renderings. I'd like to try adding `PureComponent` and rolling a release.
=> feat: try using purecomponent for html

__tests__/__snapshots__/index.test.js.snap, components/Anchor.jsx, index.js
=> style(anchor): menu item styling for doc links

__tests__/__snapshots__/magic-block-parser.test.js.snap, processor/parse/magic-block-parser.js
Remove globals from the magic block parser. This was setting compatibility to true globally.
=> fix: git rid of globals

package-lock.json, package.json
[![PR App][icn]][demo] | Fix CX-227
- Bump `@readme/syntax-highlighter` so we include [Rafe's custom scrollbar work ](https://github.com/readmeio/syntax-highlighter/pull/427)
=> chore(deps): bump @readme/syntax-highlighter

.github/workflows/codeql-analysis.yml
also ran the workflow file through a formatter (but opted to not format every file and mess with this repo's prettier setup)
=> chore(deps-dev): bump codeql scanner

components/Image/style.scss
| [![PR App][icn]][demo] | Fix CX-160 |
Fixes center aligning images with captions.
=> fix(image): center align

components/CodeTabs/style.scss
Umm, not sure how to describe this other than the title :)
=> style: add focus and active states

.github/workflows/release.yml, .releaserc
=> build: beta release channel

.github/workflows/ci.yml
Updates to `actions/upload-artifact@v3`.
=> build: update upload-artifact

__tests__/astToPlainText.test.js, __tests__/hast/index.test.js, __tests__/html.test.js, __tests__/md.test.js, __tests__/mdast.test.js, __tests__/toc.test.js, docs/table-of-contents-tests.md, example/Demo.jsx, index.jsx, package-lock.json, package.json, processor/compile/index.js, processor/compile/jsx.js
=> feat: mdx flavored TOCs

components/GlossaryItem/style.scss
We renamed this to system with apiv2
=> fix: darkmode typo

styles/gfm.scss
Updates list items to clear floats.
=> style: li clear float

README.md, __tests__/__snapshots__/disabling-tokenizers.test.js.snap, __tests__/__snapshots__/html-block-parser.test.js.snap, __tests__/__snapshots__/index.test.js.snap, __tests__/__snapshots__/link-parsers.test.js.snap, __tests__/flavored-parsers/__snapshots__/callouts.test.js.snap, __tests__/flavored-parsers/__snapshots__/code-tabs.test.js.snap, __tests__/flavored-parsers/__snapshots__/compact-headings.test.js.snap, __tests__/flavored-parsers/__snapshots__/tables.test.js.snap, __tests__/index.test.js, __tests__/transformers/__snapshots__/reusable-content.test.js.snap, __tests__/transformers/__snapshots__/single-code-tabs.test.js.snap, __tests__/transformers/__snapshots__/table-cell-inline-code.test.js.snap, index.js, options.js
Fixes outputting positional data with `hast`. Also sets the default to dump positional data.
=> fix: positional data in hast

package-lock.json, package.json
Security updates
- `@readme/syntax-highlighter` maintenance update
- override `trim` to `^1`
=> chore(deps): more security updates

package.json
=> fix: match tippy version to react-styleguidist

package.json
=> beta(deps): bump @readme/variable peer version

__tests__/transformers/reusable-content.test.js, processor/parse/reusable-content-parser.js, processor/transform/index.js, processor/transform/reusable-content.js
Fixes unwrapping the reusable content.
=> fix: wrap: false

example/RenderError.tsx, processor/transform/callouts.ts, tsconfig.json
=> Fix types release

index.js, lib/owlmoji.js, package-lock.json, processor/parse/gemoji-parser.js
Exports our `Owlmoji` class for consumption in the main app.
=> feat: export owlmoji

__tests__/flavored-compilers/tables.test.js, jest.config.js, package-lock.json, package.json, processor/compile/table.js
- Allow compiling multiple blocks within table cells
- Add prettier 2
=> fix: saving multiple blocks in tables

index.tsx
=> fix: update variable types

.github/workflows/release.yml
=> build: dont release beta docs

__tests__/compilers/compatability.test.ts, package-lock.json, package.json, processor/compile/compatibility.ts
Fixes some issus that come up during testing.
1. Close unclosed self-closing tags.
2. Handle mutli-line html comments.
=> fix: migration issues

lib/run.tsx
=> idk what happened here

__tests__/compilers/html-block.test.ts
unskipping and fixing one of the html block tests
=> fix: html block test

__tests__/compilers/html-block.test.ts
=> feat: add another html block test

processor/plugin/toc.ts
=> chore(beta): nix errant log

components/Accordion/index.tsx, components/Accordion/style.scss, components/CardsGrid/style.scss, components/index.ts
[![PR App][icn]][demo] | Fix RM-9808
- Implement an mdx built-in component for `<Accordion />`!
=> feat: accordion

components/Tabs/index.tsx, components/Tabs/style.scss, components/index.ts
[![PR App][icn]][demo] | Fix RM-9809
- new built-in `<Tabs />` component for mdx
=> feat: tabs component

components/Accordion/index.tsx, components/Accordion/style.scss, components/Cards/index.tsx, components/Cards/style.scss, components/CardsGrid/index.tsx, components/CardsGrid/style.scss, components/Tabs/style.scss, components/index.ts, example/demo.scss
[![PR App][icn]][demo] | Fix RM-10429
- Update `cards` (linkable, syntax, icon, title), `accordion` (styling, icon, semantic), `tabs` (styling)
| jsx | component |
|--------|--------|
| <img width="500" alt="image" src="https://github.com/user-attachments/assets/d89896d6-c0ed-41d4-ae62-236acd1855e9"> | <img width="500" alt="image" src="https://github.com/user-attachments/assets/f20a16ba-93cd-4d2e-a9e8-98185886ad54"> |
| <img width="500" alt="image" src="https://github.com/user-attachments/assets/4ee8dc79-cb75-4731-8bda-04b057dd0c26"> | <img width="500" alt="image" src="https://github.com/user-attachments/assets/aae8a9c1-76b3-4fae-a7da-e0d53ef85ef7"> |
| <img width="500" alt="image" src="https://github.com/user-attachments/assets/6ebacb5b-0ff3-45da-bf71-86 …
=> feat: update built-in components

components/Accordion/style.scss, components/Cards/index.tsx, components/Cards/style.scss, components/Tabs/style.scss
- tweak some component styling based on jaclyn's feedback
=> chore: update component styling

README.md
=> docs: update readme for MDX

__tests__/compilers/compatability.test.tsx, docs/images.md, processor/transform/readme-to-mdx.ts
[![PR App][icn]][demo] | Ref CX-1115
Fixes yet another image code path.
=> fix: yet another image code path

components/Image/style.scss, docs/callouts.md
To repro on prod:
https://docs.readme.com/main/docs/intro-to-readme
=> fix: missing close icon

Makefile
- fix docker build error on mac
=> fix: docker build

components/Columns/index.tsx, components/Columns/style.scss, components/index.ts, docs/built-in-components.mdx
[![PR App][icn]][demo] | Fix RM-11030
- Implement `Columns` component
=> feat: columns

components/Columns/index.tsx, components/Columns/style.scss, docs/built-in-components.mdx
[![PR App][icn]][demo] | Fix RM-11030
- Remove columns prop (calculate number of child elements instead)
- Add media query for responsiveness
=> fix: update columns

__tests__/browser/markdown.test.js
Skips a test that fails sporadically.
=> chore: skip mermaid test

components/CodeTabs/style.scss, components/TableOfContents/index.tsx
A few months ago we had a 3rd party [accessibility audit](https://docs.google.com/spreadsheets/d/1dRzxZ-AeihFDBzaMACZbFws5uS3lMR0HlWXIyS57aAA/edit?gid=51951867#gid=51951867) completed.
This PR fixes all of the critical markdown editor issues. There should be no visual changes.
=> fix: a11y audit critical issues

package-lock.json, package.json
Updates the acorn dep to match mermaid's acorn version
=> fix: update acorn

package.json
Accidentally committed this in a previous PR
=> fix: revert package name

.github/workflows/ci.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.legacy, README.md, package.json
Sets up a `v6` release branch.
This should clean up our packages dependencies where we've been aliasing `6.87.1` to various names. It should also enable us to apply bug fixes if we really need to.
=> feat: v6 release branch

.github/workflows/release.yml, .releaserc
Updates semantic release config to release `v6` branch.
Also cleans up some of the action so we don't attempt to merge to `next` or sync with readme docs.
=> chore: fix release workflow

README.md
Updates readme to reflect that we no longer alias this package in the main app.
=> chore: update link docs

package-lock.json, package.json
[![PR App][icn]][demo] | Fix RM-14044
- mermaid `v11.3.0` → `v11.12.0`
=> chore: upgrade mermaid to latest version

package-lock.json, package.json
[![PR App][icn]][demo] | Fix RM-14044
missed this from #1199
=> chore: bump optional mermaid dep
